version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DEBUG=true
      - LOG_LEVEL=INFO
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
